### PR TITLE
Modernized code.

### PR DESCRIPTION
**Pull request by awhitford**
* Added `final` declarations to member variables, when applicable.
* Replaced `addElement` and `removeElement` (`Vector`) with `add` and `remove` (`Collection`).
* Replaced `Vector.copyInto` with `Collection.toArray`.
* Replaced some old index iteration with *enhanced for loops*.
* Replaced local `Vector` variable with `ArrayList` since synchronization overhead is not necessary.
* Removed some redundant parentheses and redundant casting.
* Leveraged the `Collections.emptyEnumeration` singleton to avoid creating an empty collection.
* Removed some redundant calls to `toString`.
* Replaced `StringBuffer` with `StringBuilder`, and leveraged chaining more.

### CODE REVIEW

**Comment by awhitford** [comment]
Using `Collection` methods is a baby step towards potentially adopting more efficient alternatives to `Vector`.

**Comment by wguttmn** [comment]
Btw, I'd like to introduce a new formatter different from what Castor currently supports. Any strong prefs ?

**Comment by wguttmn** [comment]
> Using Collection methods is a baby step towards potentially adopting more efficient alternatives to Vector.

Can you expand on this statement

**Comment by awhitford** [comment]
`Vector`, `Hashtable`, and `Stack` are legacy collections that date back to Java Version 1.0 and have synchronized methods which are incredibly inefficient when you don't need threading guards.  Java 1.2 introduced the [Java Collections Framework](http://docs.oracle.com/javase/8/docs/technotes/guides/collections/index.html) with `List`, `Map` and `Set` and offered a mechanism for adding synchronization guards (like [Collections.synchronizedList](http://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedList-java.util.List-)).

I recall a comment that indicated that Castor maintained the use of `Vector` and `Hashtable` intentionally to maintain compatibility with Java 1.1.  That backwards compatibility doesn't seem very important now that compilation settings are set to 1.7; instead, I would think about what *needs* thread-safe synchronization and what does not.  (Hint:  most use-cases don't need synchronized collections.)

So if you intend to replace `Vector` with `List` and `Hashtable` with `Map`, then sticking to the `Collections` API will make that transition easier.  For example, `Vector` supports `addElement` and `add`, but `List` only supports `add`.  If you stick to the *new* API, then one just needs to redeclare the variable to gain efficiency.

**Comment by awhitford** [comment]
> Btw, I'd like to introduce a new formatter different from what Castor currently supports. Any strong prefs ?

Please clarify what kind of *formatter* you are referring to.  (Do you have a short list?)

**Comment by wguttmn** [comment]
How about https://github.com/google/styleguide ? I've used this quite frequently with only smallest modifications ...

**Comment by wguttmn** [comment]
Thanks for clarifying on that point. I was not sure whether you were referring to 1.1 collection types in general of something in particular.

**Comment by awhitford** [comment]
Oh, that _formatter_...

I generally follow the old *Sun Java Coding Conventions*, but I can't even find a current link anymore.  (It took me years to adopt the recommended _Java Style_ over my previous _C/C++ style_, but I eventually warmed up and embraced them.)  My main recommendation is to **adopt the de facto standard so that you get less friction with tools** (like IDEs and [Checkstyle](http://checkstyle.sourceforge.net/), for example).  The second most important thing is **consistency**.  (The files with 3 space indents really threw me off.)

It would appear that Google is doing a better job at maintaining their Style Guide, and [Checkstyle supports it](http://checkstyle.sourceforge.net/google_style.html), so that seems like a fine choice.

**Comment by awhitford** [comment]
By the way, Google's 2 space indentation recommendation (vs the typical 4) is actually wise long term as Java adopts features like Lambdas.  Historically, Java discouraged complexity, and a 4 space indentation helped visually express how nesting yields complexity.  However, my experience with Scala and closures leads you to naturally build embedded blocks; using Lambdas with Java will be similar, and isn't something to be discouraged.

**Comment by wguttmn** [comment]
Looks like you are sold ;-). I'll change the documentation and this available as part of the project sources (for Java at least).

**Comment by wguttmn** [comment]
Just checked in a change where I reformatted everything in castor-anttask/src/main/java with the new formatter def. Let me know your thoughts and I will do the rest.

**Comment by awhitford** [comment]
Looks good to me.

**Comment by wguttmn** [comment]
Perfect, I'll reformat all src/main/java and src/test/java folders of all modules.

**Pull request merged**
